#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
script_path="$script_dir/install_config.sh"
base_config="$script_dir/config.toml"
local_config="$script_dir/config.local.toml"
target_dir="${CODEX_HOME:-$HOME/.codex}"
target_config="$target_dir/config.toml"
state_hash="$target_dir/.config.toml.dotfiles.sha256"
state_outer_hash="$target_dir/.config.toml.dotfiles.outer.sha256"
begin_marker="# BEGIN dotfiles local Codex config"
end_marker="# END dotfiles local Codex config"

hash_file() {
    shasum -a 256 "$1" | awk '{ print $1 }'
}

write_config() {
    output_file="$1"

    {
        printf '# Generated by %s; do not edit shared settings here.\n' "$script_path"
        printf '# Shared source: %s\n' "$base_config"
        printf '# Local source: %s\n' "$local_config"
        printf '# Edit local settings only between the BEGIN/END markers below.\n'
        printf '\n'
        cat "$base_config"
        printf '\n%s\n' "$begin_marker"
        if [ -f "$local_config" ]; then
            cat "$local_config"
        fi
        printf '\n%s\n' "$end_marker"
    } > "$output_file"
}

has_local_block() {
    grep -Fxq "$begin_marker" "$1" && grep -Fxq "$end_marker" "$1"
}

strip_local_block() {
    awk -v begin="$begin_marker" -v end="$end_marker" '
        $0 == begin { inside = 1; print begin; print end; next }
        $0 == end { inside = 0; next }
        !inside { print }
    ' "$1"
}

extract_local_block() {
    awk -v begin="$begin_marker" -v end="$end_marker" '
        $0 == begin { inside = 1; found = 1; next }
        $0 == end { inside = 0; next }
        inside { print }
        END { exit found ? 0 : 1 }
    ' "$1"
}

abort_for_drift() {
    cat >&2 <<EOF
Refusing to overwrite $target_config because it has unmanaged local edits.

Move shared changes into:
  $base_config

Move machine-local changes into:
  $local_config

Then rerun:
  $script_path

After you have migrated those edits, run once with:
  CODEX_CONFIG_INSTALL_FORCE=1 $script_path
EOF
    exit 1
}

mkdir -p "$target_dir"
tmp_config=$(mktemp "$target_config.tmp.XXXXXX")
tmp_target_outer=$(mktemp "$target_config.outer.XXXXXX")
tmp_config_outer=$(mktemp "$target_config.outer.XXXXXX")
tmp_local=$(mktemp "$target_config.local.XXXXXX")
trap 'rm -f "$tmp_config" "$tmp_target_outer" "$tmp_config_outer" "$tmp_local"' EXIT

write_config "$tmp_config"

if [ -f "$target_config" ]; then
    target_hash=$(hash_file "$target_config")
    desired_hash=$(hash_file "$tmp_config")
    previous_hash=""
    previous_outer_hash=""
    if [ -f "$state_hash" ]; then
        previous_hash=$(cat "$state_hash")
    fi
    if [ -f "$state_outer_hash" ]; then
        previous_outer_hash=$(cat "$state_outer_hash")
    fi

    if [ "${CODEX_CONFIG_INSTALL_FORCE:-0}" = "1" ]; then
        :
    elif [ "$target_hash" = "$desired_hash" ]; then
        :
    elif [ -n "$previous_hash" ] && [ "$target_hash" = "$previous_hash" ]; then
        :
    elif has_local_block "$target_config"; then
        strip_local_block "$target_config" > "$tmp_target_outer"
        strip_local_block "$tmp_config" > "$tmp_config_outer"
        target_outer_hash=$(hash_file "$tmp_target_outer")
        desired_outer_hash=$(hash_file "$tmp_config_outer")
        if [ "$target_outer_hash" = "$desired_outer_hash" ] ||
            { [ -n "$previous_outer_hash" ] && [ "$target_outer_hash" = "$previous_outer_hash" ]; }; then
            extract_local_block "$target_config" > "$tmp_local"
            cp "$tmp_local" "$local_config"
            printf 'Updated %s from local block in %s\n' "$local_config" "$target_config"
            write_config "$tmp_config"
        else
            abort_for_drift
        fi
    else
        abort_for_drift
    fi
fi

mv "$tmp_config" "$target_config"
chmod 600 "$target_config"
hash_file "$target_config" > "$state_hash"
strip_local_block "$target_config" > "$tmp_config_outer"
hash_file "$tmp_config_outer" > "$state_outer_hash"
printf 'Wrote %s\n' "$target_config"
